version: "3"
services:
  app:
    build: .
    command: make test
    environment:
      - SHELL=/bin/sh
    volumes:
      - ./wrappers/:/go/src/app/wrappers/
      - ./examples/:/go/src/app/examples/
      - ./Makefile:/go/src/app/Makefile

